<?php
    if(!isset($_SESSION))
    {
        session_start();
    }
    //voltando os dados para o formulario e retirando informação desnecessaria
    if(isset($_SESSION['usuarioerror']) && !empty($_SESSION['usuarioerror']))
    {
        $usuario = $_SESSION['usuarioerror'];
        unset($_SESSION['usuarioerror']);
        array_splice($usuario, 1, 1);
    }
    else
    {
        $usuario = null;
    }

    
?>
<form method="post" action="/logando">
    <label for="email">Digite o seu email</label><br>
    <input type="text" name="email_Usuario" id="email" value="<?= (!empty($usuario) ? $usuario['email_Usuario'] : "");?>" placeholder="Email"><br>
    <label for="senha">Digite a sua senha</label><br>
    <input type="password" name="senha_Usuario" id="senha" placeholder="Senha"><br>
    <button type="submit">Logar</button>
    <a href="/cadastro"><button type="button" class="btn btn-dark">Cadastrar</button></a>
</form>