<!--<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Projeto Moda Radical</title>
    </head>
    <body>
    	<header>
			<h1> Projeto moda radical</h1>
			<label for="txtpesquisa">Pesquisar na loja</label><br>
			<input type="text" name="pesquisa" id="txtpesquisa"><br><br>
			<ul>
				<a href=login.cshtml>Login</a><br>
				<a href=pusuario.cshtml>Pagina do usuario</a><br>
				<a href=admin.cshtml>Admin</a><br>
				<a href=carrinho.cshtml>Carrinho</a><br>

			</ul>

			<hr>

		</header>
		<main>
			<p> Lorem ipsum dolor sit amet consectetur adipisicing elit.
				 Deleniti repudiandae architecto quidem sapiente!</p>
			<p>Ut ea ex anim tempor do.</p>
			<ul>
				<h2>categorias</h2>
				<a href=categoria.csHtml>Filmes/series</a>&nbsp; &nbsp;
				<a href=categoria.csHtml>esportes</a>&nbsp;&nbsp; 
				<a href=categoria.csHtml>aventura</a> &nbsp;&nbsp;
				<a href=categoria.csHtml>musica</a> &nbsp;&nbsp;
				<a href=categoria.csHtml>funny</a> &nbsp;&nbsp;
				<a href=categoria.csHtml>animais</a><br>
				<h2>Para você</h2>
				<a href=produto.cshtml>produto1</a>&nbsp;&nbsp;
				<a href=produto.cshtml>produto2</a>&nbsp;&nbsp;
				<a href=produto.cshtml>produto3</a>&nbsp;&nbsp;
				<a href=produto.cshtml>produto4</a>&nbsp;&nbsp;
				<a href=produto.cshtml>produto5</a>&nbsp;&nbsp;
				<a href=produto.html>produto6</a>&nbsp;&nbsp;<br>

			</ul>
		</main>
    </body>
</html>-->
<main class="container">
    <div id="carrossel" class="carousel slide mt-2 mb-3" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="Img/Banners/banner_camisa.jpg" class="d-block w-100 h-100 center-img" alt=" ">
            </div>
            <div class="carousel-item">
                <img src="Img/Banners/Teste_carrossel_1724x260.png" class="d-block w-100" alt=" ">
            </div>
            <div class="carousel-item">
                <img src="Img/Banners/teste_de_banner_1920x256.png" class="d-block w-100 center-img" alt=" ">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carrossel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carrossel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Próximo</span>
        </button>
    </div>
    <!--banner-->
    <section class="container mt-5">
        <a href="#"><img class ="col-12" src="../Img/Banners/banner_camisa.jpg" alt="banner ilustrativo"></a>
    </section>

    <div class="container" id="separador">
        <div class="row justify-content-center">
            <div class="col-3 sep-esq">
                <div class="rot-180">
                    <img src="Img\Separadores\folha_de_loro.svg">
                </div>
            </div>
            <div class="col-4">
                <h2 class="text-center fs-2 fw-bold my-2 ">Categorias</h2>
            </div>
            <div class="col-3 sep-dir">
                <img src="Img\Separadores\folha_de_loro.svg">
            </div>
            
        </div>

    </div>    
    <div class="d-inline-flex" id="Categorias">
        <div class="text-center fs-4 fw-bold">
            <a href="#" class="mx-3"><img src="Img\Categorias\gato_jedi.jpg" alt="gato jedi" class="arredondar-imagem make-square"></a>
            <span>Geek</span>
        </div>

        <div class="text-center fs-4 fw-bold">
            <a href="#" class="mx-3"><img src="Img\Categorias\NBA_kobe.jpg" alt="coube" class="arredondar-imagem make-square"></a>
            <span>Esportes</span>
        </div>

        <div class="text-center fs-4 fw-bold">
            <a href="#" class="mx-3"><img src="Img\Categorias\singapura.jpg" alt="seringa pura" class="arredondar-imagem make-square"></a>
            <span>Aventura</span>
        </div>

        <div class="text-center fs-4 fw-bold">
            <a href="#" class="mx-3"><img src="Img\Categorias\Avenged_sevenfold.jpg" alt="avistado sete vezes" class="arredondar-imagem make-square"></a>
            <span>Bandas</span>
        </div>

        <div class="text-center fs-4 fw-bold">
            <a href="#" class="mx-3"><img src="Img\Categorias\procrastinators_funny_print.jpg" alt="MEME BAUM RARARA" class="arredondar-imagem make-square"></a>
            <span>Funny</span>
        </div>

        <div class="text-center fs-4 fw-bold">
            <a href="#" class="mx-3"><img src="Img\Categorias\caballo.jpg" alt="Juan" class="arredondar-imagem make-square"></a><br>
            <span>Animais</span>
        </div>

    </div>
    <div class="container" id="separador">
        <div class="row justify-content-center">
            <div class="col-3 sep-esq">
                <div class="rot-180">
                    <img src="Img\Separadores\folha_de_loro.svg">
                </div>
            </div>
            <div class="col-4">
                <h2 class="text-center fs-2 fw-bold my-2">Para você</h2>
            </div>
            <div class="col-3 sep-dir">
                <img src="Img\Separadores\folha_de_loro.svg">
            </div>
            
        </div>

    </div>
    
    <div class="d-inline-flex" id="Camisas">
        <div>
            <a href="#" class="mx-2"><img class="make-retangle zoom" src="Img\Camisas\caveira.jpg" alt="caviar"></a>
        </div>

        <div>
            <a href="#" class="mx-2"><img class="make-retangle zoom" src="Img\Camisas\Criança_radioativa.jpg" alt="chernobyl"></a>
        </div>

        <div>
            <a href="#" class="mx-2"><img  class="make-retangle zoom" src="Img\Camisas\Dragao.jpg" alt="Shenlong de camelo"></a>
        </div>

        <div>
            <a href="#" class="mx-2"><img class="make-retangle zoom" src="Img\Camisas\kitsune_masks.jpg" alt="otaku"></a>
        </div>

        <div>
            <a href="#" class="mx-2"><img class="make-retangle zoom" src="Img\Camisas\Monster.jpg" alt="pepe radioativo"></a>
        </div>
    </div>

</main>
